### ISSUE TITLE
Random black specks on output compared to original DPIR

### ISSUE THREAD

**Issue by khang06** [HolyWu/vs-dpir#11]
I can't give a better explanation than the title, so the issue can be clearly seen in [this comparison](https://slow.pics/c/sT9rwfif). The other image in the comparison is the standalone DPIR, and the issue only happens with `task='deblock'`. `task='denoise'` works fine.

**Comment by HolyWu** [comment]
Please provide an unprocessed sample for investigation.

**Comment by khang06** [comment]
https://cdn.discordapp.com/attachments/872690735152005200/891585644076363826/01_3144.png

**Comment by HolyWu** [comment]
I cannot reproduce that artifacts. What strength did you set? Are you using the latest v1.5? Does v1.4 or v1.3 have the same issue?

**Comment by HolyWu** [comment]
Is it also reproducible for you if you use this `01_3144.png` as source rather than use the original video file as source?

**Comment by khang06** [comment]
Nope, using that image doesn't actually work. However, it was figured out that doing `YUV420P8 -> RGBS` artifacted while `YUV420P8 -> RGB24 -> RGBS` didn't. A test video file can be found [here](https://cdn.discordapp.com/attachments/872690735152005200/891599644419833876/sample.mp4) and it was used with the following script:
```
rgb = jp.resize.Spline36(format=vs.RGBS)
deblock = DPIR(rgb, strength=12, task='deblock')
```

**Comment by NSQY** [comment]
Hi, I have a much more extreme example: https://slow.pics/c/inY0pC4F

Confirmed that clamping before DPIR fixes the issue.

**Comment by HolyWu** [comment]
Good finding. I'll explicitly clamp the pixel value for 'deblock' task then.

**Comment by LightArrowsEXE** [comment]
This issue seems to still persist.

```py
from vsutil import depth
import lvsfunc as lvf

src = depth(src, 16).std.Limiter(16 << 8, [235 << 8, 240 << 8], [0, 1, 2])
debl = lvf.deblock.vsdpir(src, matrix=1, cuda=True)  # Simple vsdpir wrapper. default: debl strength=25
```
`src.set_output(0)` (with frameprops)
![image](https://user-images.githubusercontent.com/42927908/135696899-fd2fe672-07a8-45b2-88df-e26264ce5d37.png)

`debl.set_output(1)` (with frameprops)
![image](https://user-images.githubusercontent.com/42927908/135696962-b49b7ed5-e1c0-45c0-94f2-881ba8672fcf.png)

As you can see here, it still creates those weird dots.
![image](https://user-images.githubusercontent.com/42927908/135697003-108dbff9-5d99-47a5-952f-464f64571024.png)
![image](https://user-images.githubusercontent.com/42927908/135697008-e87d3b53-1992-42ab-81e7-194ac2baf187.png)

It seems that even if the input is limited, the output may enter illegal ranges. I'm not at all sure what the cause behind this could be.

**Comment by HolyWu** [comment]
I cannot reproduce it using the clean frame png even though I intentionally convert it to YUV420P16 first. Could you provide an unprocessed one-frame y4m since the png was already converted to RGB24?

**Comment by LightArrowsEXE** [comment]
Sorry, it seems I tried installing it from pypi so fast when the commits were pushed that it wasn't updated there yet and I didn't realise. My bad!
